[package]
name = "bevy_4x_camera"
version = "0.1.0"
authors = ["Sarthak Singh <ss269@uw.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4"
bevy_mod_picking = "0.3.3"
rand = "0.8"